name: Build

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # Step 4: Compile Achievement Watchdog executable
      - name: Build Achievement Watchdog
        run: |
          pyinstaller --noconsole --add-data "assets\\achievement.png;." --icon "assets\\achievement.ico" --name "Achievement Watchdog" --optimize 2 --onefile .\achievement_watchdog.py

      # Step 5: Compile Achievement Viewer executable
      - name: Build Achievement Viewer
        run: |
          pyinstaller --icon "assets\\achievement_av.ico" --name "Achievement Viewer" --optimize 2 --onefile .\achievement_viewer.py

      # Step 6: Verify and Rename the dist directory
      - name: Rename dist directory
        run: |
          ren dist "Achievement Watchdog"

      # Step 7: Add additional files to the renamed directory
      - name: Copy additional files
        run: |
          copy .env "Achievement Watchdog\\"
          copy assets\\achievement_sound.mp3 "Achievement Watchdog\\"

      # Step 9: Upload the artifact for later download
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Achievement.Watchdog
          path: 'Achievement Watchdog\'
          compression-level: 9
          include-hidden-files: true
          if-no-files-found: error
